/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package PROG_ICE_task_2;
import javax.swing.*;

public class App {
   
  
    public static void main(String[] args) {
       final int Numbers = 20;
       int[] Values = new int[Numbers];
       String input;
       StringBuilder results = new StringBuilder("Entered values:\n");
       
       for (int i = 0; i < Values.length; i++)
       {
           input = JOptionPane.showInputDialog(null, "Enter your values: " + (i + 1));
           Values[i] = Integer.parseInt(input);
       }
       for (int i = 0; i < Values.length; i++)
       {
           results.append("Student ").append(i + 1).append(": ").append(Values[i]).append("\n");
       }
    }
}
